# Generated by Django 3.2.12 on 2022-05-01 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='diagnosis',
            options={'ordering': ['-created_at'], 'verbose_name': 'Diagnosis', 'verbose_name_plural': 'Diagnoses'},
        ),
        migrations.AlterUniqueTogether(
            name='diagnosis',
            unique_together={('category_code', 'diagnosis_code')},
        ),
    ]
