# Generated by Django 3.2.12 on 2022-05-02 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0002_auto_20220501_1347'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='diagnosis',
            options={'ordering': ('-created_at',), 'verbose_name': 'Diagnosis', 'verbose_name_plural': 'Diagnoses'},
        ),
        migrations.AlterField(
            model_name='diagnosis',
            name='category_code',
            field=models.CharField(max_length=10),
        ),
    ]
